# Generated by Django 4.2.2 on 2023-11-25 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='inbox',
        ),
    ]
