# Generated by Django 4.2.2 on 2024-05-20 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contactlist_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactlist',
            name='picture',
        ),
    ]
