# Generated by Django 4.2.2 on 2023-08-19 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_job_user_jobcategory_created_alter_rating_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcategory',
            name='created',
        ),
    ]
