# Generated by Django 4.2.2 on 2024-06-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_skill_skilla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brief',
            name='attach_files',
            field=models.FileField(blank=True, default=None, upload_to='project_description_files'),
        ),
    ]
