# Generated by Django 4.2.2 on 2024-05-30 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_contactlist_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('amount', models.IntegerField(default=0)),
                ('verified', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=12, null=True)),
                ('channel', models.CharField(blank=True, max_length=10, null=True)),
                ('card_type', models.CharField(blank=True, max_length=10, null=True)),
                ('time_of_payment', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
