# Generated by Django 4.2.2 on 2024-06-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_brief_attach_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='skill_images'),
        ),
    ]
