# Generated by Django 4.2.2 on 2023-11-26 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_inbox_chatmessage_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inbox_sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
