# Generated by Django 4.2.2 on 2023-07-24 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_material_training'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Training',
        ),
        migrations.DeleteModel(
            name='Facilitator',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CLIENT', 'Client'), ('SKILLAS', 'Skillas')], max_length=50),
        ),
    ]
