# Generated by Django 4.2.2 on 2023-11-26 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_inbox_sender_alter_inbox_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbox',
            name='sender',
        ),
        migrations.AlterField(
            model_name='inbox',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
