# Generated by Django 4.2.2 on 2024-06-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='verified',
            new_name='reference',
        ),
        migrations.AddField(
            model_name='payment',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
