# Generated by Django 4.2.2 on 2023-08-21 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_clientrequest_created_jobcategory_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='user',
        ),
    ]
