# Generated by Django 4.2.2 on 2024-06-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_verified_payment_reference_payment_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='message',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
