# Generated by Django 4.2.3 on 2023-07-25 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='rating',
        ),
        migrations.AddField(
            model_name='skill',
            name='base_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, choices=[(1, '*'), (2, '**'), (3, '***'), (4, '****'), (5, '*****')], null=True)),
                ('ratee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ratings_reciever', to='main.skillas')),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ratings_giver', to='main.clients')),
            ],
        ),
    ]
