# Generated by Django 4.2.3 on 2023-09-15 05:40

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_job_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillaProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, choices=[('NIGERIA', 'Nigeria'), ('UK', 'United Kingdom'), ('USA', 'United States of America'), ('GHANA', 'Ghana')], max_length=20, null=True)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('current_location', models.CharField(blank=True, max_length=20, null=True)),
                ('experience', models.IntegerField(blank=True, null=True, verbose_name='Years of Experience')),
                ('certifications', models.CharField(blank=True, max_length=256, null=True, verbose_name='Education and Certification (Optional)')),
                ('portfolio', models.URLField(blank=True, null=True, verbose_name='Provide url/link or file upload')),
                ('professional_profiles_links', models.CharField(blank=True, max_length=256, null=True)),
                ('hourly_rate', models.IntegerField(verbose_name='Hourly_rate aor salary')),
                ('activated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.user',),
            managers=[
                ('company', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CLIENT', 'Client'), ('SKILLAS', 'Skillas'), ('COMPANY', 'Company')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AddField(
            model_name='skillaprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
