# Generated by Django 4.2.2 on 2024-07-01 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_skill_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_certified',
            field=models.BooleanField(default=False),
        ),
    ]
