# Generated by Django 4.2.2 on 2023-09-16 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_skillaprofile_company_alter_user_role_delete_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillaprofile',
            name='terms_and_conditions',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, choices=[('NIGERIA', 'Nigeria'), ('UK', 'United Kingdom'), ('USA', 'United States of America'), ('GHANA', 'Ghana')], max_length=20, null=True)),
                ('current_location', models.CharField(blank=True, max_length=20, null=True)),
                ('home_address', models.CharField(blank=True, max_length=256, null=True)),
                ('occupation', models.CharField(blank=True, max_length=50, null=True)),
                ('id_card', models.ImageField(upload_to='id_cards_for_kyc')),
                ('services_needed', models.CharField(blank=True, max_length=256, null=True)),
                ('terms_and_conditions', models.BooleanField(blank=True, default=False)),
                ('activated', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
