# Generated by Django 4.2.2 on 2023-08-03 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_skill_rating_skill_base_price_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='city',
            new_name='current_location',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='rater',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='ratee',
            new_name='skilla',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.job'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, choices=[('NIGERIA', 'Nigeria'), ('UK', 'United Kingdom'), ('USA', 'United States of America'), ('GHANA', 'Ghana')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reason',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.CreateModel(
            name='MatchSkillaToClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(blank=True, max_length=256, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payer', to='main.clients')),
                ('skilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobber', to='main.skillas')),
            ],
        ),
    ]
