# Generated by Django 4.2.2 on 2024-06-07 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_payment_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='skilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skilla_paid', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='skilla_img',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_payer', to=settings.AUTH_USER_MODEL),
        ),
    ]
