# Generated by Django 4.2.2 on 2023-12-03 00:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_chatmessage_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='skilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobber', to=settings.AUTH_USER_MODEL),
        ),
    ]
