# Generated by Django 4.2.2 on 2024-06-07 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_payment_skilla_payment_skilla_img_alter_payment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='skilla_img',
        ),
    ]
