# Generated by Django 4.2.2 on 2023-12-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_order_client_alter_order_skilla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='notification',
            field=models.IntegerField(blank=True, max_length=256, null=True),
        ),
    ]
