# Generated by Django 4.2.2 on 2024-08-05 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_user_is_certified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skillaprofile',
            old_name='identification',
            new_name='passport_photo',
        ),
        migrations.RemoveField(
            model_name='skillaprofile',
            name='hourly_rate',
        ),
        migrations.RemoveField(
            model_name='skillaprofile',
            name='terms_and_conditions',
        ),
        migrations.AddField(
            model_name='skillaprofile',
            name='Postal_code',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='skillaprofile',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='skillaprofile',
            name='house_address',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='skillaprofile',
            name='region',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='skillaprofile',
            name='street_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Compliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complied', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
