# Generated by Django 4.2.2 on 2023-09-21 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_skillaprofile_terms_and_conditions_clientprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillaprofile',
            name='hourly_rate',
            field=models.IntegerField(blank=True, null=True, verbose_name='Hourly_rate or salary'),
        ),
    ]
