# Generated by Django 4.2.2 on 2023-09-24 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_skillaprofile_hourly_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, choices=[('NIGERIA', 'Nigeria'), ('UK', 'United Kingdom'), ('USA', 'United States of America'), ('GHANA', 'Ghana')], max_length=100, verbose_name='Location (City/Country)')),
                ('state', models.CharField(blank=True, max_length=50)),
                ('industry', models.CharField(blank=True, max_length=100, verbose_name='Industry or Business Type')),
                ('company_size', models.IntegerField(blank=True, null=True, verbose_name='company size (Number of Employees)')),
                ('services', models.CharField(blank=True, max_length=200, null=True, verbose_name='Describe the services or skills needed (Optional)')),
                ('work_history_with_freelancer', models.BooleanField(blank=True, null=True, verbose_name='Have you worked with a freelancer or skilled workers Before')),
                ('terms_and_conditions', models.BooleanField(blank=True, default=False)),
                ('activated', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Material',
        ),
    ]
