# Generated by Django 4.2.2 on 2024-08-06 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_identification_skillaprofile_passport_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillaprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skillas_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
