# Generated by Django 4.2.2 on 2023-12-05 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_order_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='notification',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
