# Generated by Django 4.2.2 on 2024-06-07 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_payment_skilla_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='skilla_image',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
