# Generated by Django 4.2.2 on 2023-10-16 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_companyprofile_delete_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='skill_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.jobcategory'),
        ),
        migrations.CreateModel(
            name='TrainingAndCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_learned', models.CharField(blank=True, max_length=256, null=True)),
                ('grade', models.CharField(blank=True, max_length=128, null=True)),
                ('assessed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.skillas')),
            ],
        ),
        migrations.CreateModel(
            name='AboutSkilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(max_length=150)),
                ('work_experience', models.CharField(blank=True, max_length=128, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.skillas')),
            ],
        ),
    ]
