# Generated by Django 4.2.2 on 2024-08-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_skillaprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillaprofile',
            name='id_card',
            field=models.ImageField(blank=True, null=True, upload_to='skillas_id_cards_for_kyc'),
        ),
        migrations.AddField(
            model_name='skillaprofile',
            name='nin',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='skillaprofile',
            name='passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to='passport_photo'),
        ),
    ]
