# Generated by Django 4.2.2 on 2023-10-17 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_skill_skill_category_trainingandcertification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingandcertification',
            name='cert_earned',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainingandcertification',
            name='skill_learned',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
