# Generated by Django 4.2.2 on 2023-12-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_order_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='decline',
            field=models.BooleanField(default=False),
        ),
    ]
