# Generated by Django 4.2.2 on 2024-06-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_wallet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='wallet',
            new_name='main',
        ),
        migrations.AddField(
            model_name='wallet',
            name='withdrawn',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
