# Generated by Django 4.2.2 on 2023-12-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_order_decline'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='skill_image',
            field=models.ImageField(blank=True, upload_to='skill_images'),
        ),
    ]
