# Generated by Django 4.2.2 on 2024-08-31 10:04

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_blogcategory_blogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='company_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='company size (Number of Employees)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_no',
            field=models.PositiveIntegerField(default=main.models.order_number),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order_no',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='skillaprofile',
            name='experience',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Years of Experience'),
        ),
    ]
