# Generated by Django 4.2.2 on 2023-12-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_skill_skill_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='skill_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='skill_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='skill_level',
            new_name='level',
        ),
        migrations.AddField(
            model_name='skill',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
