# Generated by Django 4.2.2 on 2024-01-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_skill_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillaprofile',
            name='certifications',
        ),
        migrations.AddField(
            model_name='skillaprofile',
            name='identification',
            field=models.ImageField(blank=True, null=True, upload_to='skillas_id_cards_for_kyc'),
        ),
        migrations.AlterField(
            model_name='skillaprofile',
            name='portfolio',
            field=models.URLField(blank=True, null=True, verbose_name='links to your works'),
        ),
    ]
