# Generated by Django 4.2.2 on 2023-10-26 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_profilepicture_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='services_needed',
        ),
    ]
