# Generated by Django 4.2.2 on 2024-06-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='pending',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
