# Generated by Django 4.2.2 on 2024-01-06 15:37

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_skillaprofile_certifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientrequest',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_size',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='company size (Number of Employees)'),
        ),
        migrations.AlterField(
            model_name='job',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='notification',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_no',
            field=models.PositiveSmallIntegerField(default=main.models.order_number),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='base_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skillaprofile',
            name='experience',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Years of Experience'),
        ),
        migrations.AlterField(
            model_name='skillaprofile',
            name='hourly_rate',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Hourly_rate or salary'),
        ),
    ]
