# Generated by Django 4.2.2 on 2024-01-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_clientrequest_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='activate',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
