# Generated by Django 4.2.2 on 2024-06-09 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_order_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_status',
        ),
    ]
