# Generated by Django 4.2.2 on 2023-10-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_brief'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brief',
            name='budget',
            field=models.IntegerField(blank=True),
        ),
    ]
