# Generated by Django 4.2.2 on 2024-06-10 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order_no',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
