# Generated by Django 4.2.2 on 2023-10-28 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_brief_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcategory',
            name='created',
        ),
        migrations.RemoveField(
            model_name='jobcategory',
            name='creator',
        ),
    ]
