# Generated by Django 4.2.2 on 2023-10-28 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_jobcategory_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcategory',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
