# Generated by Django 4.2.2 on 2024-02-03 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_message_remove_inbox_message_remove_inbox_owner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='recipient',
            new_name='receiver',
        ),
    ]
