# Generated by Django 4.2.2 on 2024-06-11 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_userreview_delete_company_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreview',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
