# Generated by Django 4.2.2 on 2023-10-28 21:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_brief_skilla_alter_brief_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brief',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
