# Generated by Django 4.2.2 on 2023-10-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_brief_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brief',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
