# Generated by Django 4.2.2 on 2023-11-01 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_brief_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='skillaReachoutToClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('budget_flexible', models.BooleanField(default=False)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.jobcategory')),
                ('skilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skilla_skilla_reachout_to_client', to='main.skillas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_skilla_reachout_to_client', to='main.clients')),
            ],
        ),
    ]
