# Generated by Django 4.2.2 on 2023-11-01 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_skillareachouttoclient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillareachouttoclient',
            name='budget_flexible',
        ),
        migrations.AddField(
            model_name='skillareachouttoclient',
            name='budget',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
