# Generated by Django 4.2.2 on 2023-11-02 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_remove_skillareachouttoclient_budget_flexible_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillareachouttoclient',
            name='skilla',
        ),
        migrations.AddField(
            model_name='skillareachouttoclient',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skilla_skilla_reachout_to_client', to='main.clients'),
        ),
        migrations.AlterField(
            model_name='skillareachouttoclient',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_skilla_reachout_to_client', to='main.skillas'),
        ),
    ]
