# Generated by Django 4.2.2 on 2024-02-27 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_contactlist_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactList',
        ),
    ]
