# Generated by Django 4.2.2 on 2024-02-27 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_contactlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactList',
        ),
    ]
