# Generated by Django 4.2.2 on 2023-11-24 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_messaginguser_chatmessage_timestamp_delete_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='message',
            field=models.ManyToManyField(to='main.chatmessage'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='MessagingUser',
        ),
    ]
